#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# (c) ACE 

import os

class Config(object):
    # get a token from @BotFather
    pass
    """
    BOT_TOKEN = os.environ.get("BOT_TOKEN", "7821208337:AAG12bK7XkDuSFIgXP-2FypgjK9Y7Vq2ahw")
    API_ID = int(os.environ["API_ID", 23713783]
    API_HASH = os.environ["API_HASH", "2daa157943cb2d76d149c4de0b036a99"]
    AUTH_USERS = "5487643307"""
# jisko bhi is repo ko deploy karne me error aa raha ho ( https://t.me/Stubborn1223 ) ye mere TG ka id ha message karke iska screen shot send kar dena me error solve kar dunga. 
